name: Pull Request from Backend
on:
  push:
    branches-ignore:
      - master

permissions:
  contents: write

jobs:
  auto-pull-request:
    name: Open Pull Request
    runs-on: ubuntu-latest
    steps:
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          title: Update from backend
          body: This is an automated pull request from the backend.