name: Pull Request from Backend
on:
  push:
    branches:
      - updatefrombackend*

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  pull-requests: write

jobs:
  auto-pull-request:
    name: Open Pull Request
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Create Pull Request
        env:
          TITLE: "Update from backend"
          BODY: "This PR merges the change request from the backend into the main branch."
          BRANCH_NAME: ${{ github.ref }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr create --base main --head "$BRANCH_NAME" --title "$TITLE" --body "$BODY"