name: Pull Request from Backend
on:
  push:
    branches:
      - updatefrombackend*

jobs:
  auto-pull-request:
    name: Open Pull Request
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          assignees: sinaatalay, Klingler98
          title: Update from backend
          body: This is an automated pull request from the backend.
          token: ${{ secrets.TOKEN }}
          