name: Pull Request from Backend
on:
  push:
    branches:
      - update/publications/*

jobs:
  create-pull-request:
    name: Create a pull request
    uses: ./.github/workflows/pull-request.yaml
    with:
      branch-name: ${{ github.ref }}
      title: "Update publications"
      body: "A request has been made to update the publications list."