name: Update Gallery
on:
  push:
    branches:
      - update/gallery/*

jobs:
  create-pull-request:
    name: Create a pull request
    uses: ./.github/workflows/pull-request.yaml
    with:
      branch-name: ${{ github.ref }}
      title: "Update gallery"
      body: "A request has been made to update the gallery."